### ISSUE TITLE
Program "mpv" not found. Please install it.

### ISSUE THREAD

**Issue by ninko76** [justchokingaround/jerry#67]
When I try to run jerry it says that I do not have mpv installed. I have it installed with scoop but it seems like jerry does not detect it. Please help

**Comment by justchokingaround** [comment]
`jerry -e` and change the player to be `player=mpv.exe`

**Comment by ninko76** [comment]
![Screenshot 2024-05-01 095540](https://github.com/justchokingaround/jerry/assets/103625285/f37d0f02-941e-4a48-a0ac-0cf3eb235b8d)
Worked but now when i type `jerry` it thinks for a second then goes back to enter command. I did get the anime selector when I typed:  `jerry -l spanish cyberpunk edgerunners --number 2 --json` but after selectinga show nothing happened.

**Comment by YuuOrKillua** [comment]
Mine has the same error, but not even adding the full path is working player="NOTSHOWINGFORSECURITYREASONS\scoop\apps\mpv\current\mpv.exe".

**Comment by justchokingaround** [comment]
youre not supposed to specify the full path, just `mpv.exe`

**Comment by YuuOrKillua** [comment]
yeah, but this has my last try I tried "mpv.exe", "mpv" and "Full path".

**Comment by justchokingaround** [comment]
oh wait i just realized you're running it from System32. just run `cd` in your terminal, and then try running jerry again, it should find the player in path just fine then

**Comment by YuuOrKillua** [comment]
im not the op of this post im running mine in my user but the same error occurs even if im in the same dir that jerry is in.
![jerryTest](https://github.com/justchokingaround/jerry/assets/81570526/a90f384d-f8d3-4cb0-abe0-9c478e5f7de3)

**Comment by justchokingaround** [comment]
try adding bash to windows terminal

![image](https://github.com/justchokingaround/jerry/assets/44473782/f260f10a-4eed-4c91-8380-e866d4f32f4a)

**Comment by YuuOrKillua** [comment]
Did everything you said.
![image](https://github.com/justchokingaround/jerry/assets/81570526/843b51c0-d48d-47b3-b881-fb54b893c4d2)

**Comment by YuuOrKillua** [comment]
And here is how mine .config is.
![image](https://github.com/justchokingaround/jerry/assets/81570526/dca8246b-2bc8-4a71-9ac8-1328db44f0d9)

**Comment by justchokingaround** [comment]
can you update to the latest version, it should be fixed now: `jerry -u` (run ur terminal as admin first)

**Comment by YuuOrKillua** [comment]
Oh sorry my bad. I got it, my mistake now it is working sorry.

**Comment by justchokingaround** [comment]
i just pushed the code 2 mins ago, no worries. it's a bug i didn't notice before. @ninko76 can you check my previous comment and lmk if it fixed your issue?

**Comment by YuuOrKillua** [comment]
well it works now but i think mpv is still not working (for me).
![image](https://github.com/justchokingaround/jerry/assets/81570526/f16ca3aa-80b0-40eb-af8e-ec581c0855fc)

**Comment by justchokingaround** [comment]
oh yeah wait, i somehow fucked up a previous commit i think lol. also you should rename jerry.sh to jerry in path `mv /usr/bin/jerry.sh /usr/bin/jerry`

**Comment by YuuOrKillua** [comment]
This wont cause a bug?
![image](https://github.com/justchokingaround/jerry/assets/81570526/824f97cc-62a7-4ea9-83d4-638990ec92a1)

**Comment by justchokingaround** [comment]
it shouldn't

**Comment by justchokingaround** [comment]
idk how powershell works so i can't help u much with that. if u use it from the windows terminal with bash, then i can help. also i just fixed the mpv bug, it should work fine now

**Comment by YuuOrKillua** [comment]
Oh okay yeah in bash works fine at least the jerry thing im going to update it.

**Comment by YuuOrKillua** [comment]
I have a question, in my powershell i can call mpv and it shows me that its there:
![image](https://github.com/justchokingaround/jerry/assets/81570526/be3bcee4-1514-4dac-ae53-169e5e9a5346)
But in bash it gives me this:
![image](https://github.com/justchokingaround/jerry/assets/81570526/50704ea0-89ce-4177-bd2b-2706aac90019)

Or am I just writing wrong for bash.

**Comment by justchokingaround** [comment]
what you can do is just symlink mpv.exe to mpv in bash, since you installed it with scoop. `ln -sf $(which mpv.exe) /usr/bin/mpv`

**Comment by YuuOrKillua** [comment]
I did what you told me to and yes mpv now is working on bash the jerry is not giving the mpv not found.
![image](https://github.com/justchokingaround/jerry/assets/81570526/5c2a86e2-536e-4ce9-b9a8-7b31a86b05f8)
But still does not work. (I tried to change "mpv.exe" for "mpv" none worked)

**Comment by justchokingaround** [comment]
can u send me the last snippet of the log so i can check where it fails? just don't accidentally leak your anilist token.

```sh
sh -x $(which jerry)
```

**Comment by YuuOrKillua** [comment]
barbo@DESKTOP-9F2VUN1 MINGW64 ~/bin
$ sh -x $(which jerry)
+ JERRY_VERSION=1.9.9
+ anilist_base=https://graphql.anilist.co
+ config_file=/c/Users/barbo/.config/jerry/jerry.conf
+ jerry_editor=
+ tmp_dir=/tmp/jerry
+ tmp_position=/tmp/jerry_position
+ trap cleanup EXIT INT TERM
+ applications=/c/Users/barbo/.local/share/applications/jerry
+ images_cache_dir=/tmp/jerry/jerry-images
+ command -v bat
+ display=less
+ case "$(uname -s)" in
++ uname -s
+ separator=';'
+ path_thing=
+ sed=sed
+ command -v notify-send
+ notify=false
+ dep_ch grep sed curl fzf mpv
+ for dep in "$@"
+ command -v grep
+ for dep in "$@"
+ command -v sed
+ for dep in "$@"
+ command -v curl
+ for dep in "$@"
+ command -v fzf
+ for dep in "$@"
+ command -v mpv
+ '[' '' = true ']'
+ configuration
+ '[' -n '' ']'
+ config_dir=/c/Users/barbo/.config/jerry
+ '[' -n '' ']'
+ data_dir=/c/Users/barbo/.local/share/jerry
+ '[' '!' -d /c/Users/barbo/.local/share/jerry ']'
+ '[' -f /c/Users/barbo/.config/jerry/jerry.conf ']'
+ . /c/Users/barbo/.config/jerry/jerry.conf
++ player=mpv
++ player_arguments=
++ chafa_options=
++ show_adult_content=false
++ provider=yugen
++ download_dir=/c/Users/barbo/bin
++ manga_dir=/c/Users/barbo/.local/share/jerry/jerry-manga
++ manga_format=image
++ manga_opener=feh
++ history_file=/c/Users/barbo/.local/share/jerry/jerry_history.txt
++ subs_language=english
++ use_external_menu=false
++ image_preview=false
++ json_output=false
++ sub_or_dub=sub
++ score_on_completion=false
++ discord_presence=false
++ presence_script_path=jerrydiscordpresence.py
+ '[' -z mpv ']'
+ '[' -z yugen ']'
+ '[' -z /c/Users/barbo/bin ']'
+ '[' -z /c/Users/barbo/.local/share/jerry/jerry-manga ']'
+ '[' -z image ']'
+ '[' -z feh ']'
+ '[' -z /c/Users/barbo/.local/share/jerry/jerry_history.txt ']'
+ '[' -z english ']'
++ printf %s english
++ cut -c2-
+ subs_language=nglish
+ '[' -z false ']'
+ '[' -z false ']'
+ '[' -z false ']'
+ '[' -z sub ']'
+ '[' -z false ']'
+ '[' '' = false ']'
+ '[' -z false ']'
+ '[' -z jerrydiscordpresence.py ']'
+ case "$(uname -s)" in
++ uname -s
+ '[' -z '' ']'
+ chafa_options='-f symbols'
+ '[' -z false ']'
+ query=
+ '[' 0 -gt 0 ']'
++ printf %s ''
++ tr ' ' -
++ sed 's/^-//g'
+ query=
+ case "$provider" in
+ provider=yugen
+ '[' false = true ']'
+ main
+ '[' -z '' ']'
+ check_credentials
+ '[' -f /c/Users/barbo/.local/share/jerry/anilist_token.txt ']'
++ cat /c/Users/barbo/.local/share/jerry/anilist_token.txt
+ access_token=$'\026\026'
+ '[' -z $'\026\026' ']'
+ '[' -f /c/Users/barbo/.local/share/jerry/anilist_user_id.txt ']'
++ cat /c/Users/barbo/.local/share/jerry/anilist_user_id.txt
+ user_id=
+ '[' -z $'\026\026' ']'
+ '[' -z '' ']'
++ curl -s -X POST https://graphql.anilist.co -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Authorization: Bearer ' -d '{"query":"query { Viewer { id } }"}'
++ sed -nE 's@.*"id":([0-9]*).*@\1@p'
+ user_id=
+ echo ''
+ '[' -z $'\026\026' ']'
+ '[' -z '' ']'
+ exit 1
+ cleanup
+ rm -rf /tmp/jerry
+ '[' false = true ']'

**Comment by justchokingaround** [comment]
oh, ure not logged in properly, something failed. do `rm -rf ~/.local/share/jerry` and try to login again

**Comment by YuuOrKillua** [comment]
Oh i did is working now that option did not apear the last time i tried could be because i did it in powershell?

**Comment by justchokingaround** [comment]
yeah it could be. ps causes unexpected behavior and im not knowledgeable enough to explain why some stuff may or may not happen when using it

**Comment by ninko76** [comment]
> i just pushed the code 2 mins ago, no worries. it's a bug i didn't notice before. @ninko76 can you check my previous comment and lmk if it fixed your issue?

It's still the same, should I reinstall it somehow?
![Screenshot 2024-05-03 110524](https://github.com/justchokingaround/jerry/assets/103625285/681a757a-249a-4b49-bd2e-78efd0a1f062)

**Comment by ninko76** [comment]
Or is there a log I can get you?

**Comment by justchokingaround** [comment]
yeah just run `sh -x $(which jerry)` and send me the last part (make sure u don't send ur token)

**Comment by ninko76** [comment]
nikot@DESKTOP-RM3F5VV MINGW64 ~
$ sh -x $(which jerry)
+ JERRY_VERSION=1.9.9
+ anilist_base=https://graphql.anilist.co
+ config_file=/c/Users/nikot/.config/jerry/jerry.conf
+ jerry_editor=
+ tmp_dir=/tmp/jerry
+ tmp_position=/tmp/jerry_position
+ trap cleanup EXIT INT TERM
+ applications=/c/Users/nikot/.local/share/applications/jerry
+ images_cache_dir=/tmp/jerry/jerry-images
+ command -v bat
+ display=less
+ case "$(uname -s)" in
++ uname -s
+ separator=';'
+ path_thing=
+ sed=sed
+ command -v notify-send
+ notify=false
+ dep_ch grep sed curl fzf
+ for dep in "$@"
+ command -v grep
+ for dep in "$@"
+ command -v sed
+ for dep in "$@"
+ command -v curl
+ for dep in "$@"
+ command -v fzf
+ '[' '' = true ']'
+ configuration
+ '[' -n '' ']'
+ config_dir=/c/Users/nikot/.config/jerry
+ '[' -n '' ']'
+ data_dir=/c/Users/nikot/.local/share/jerry
+ '[' '!' -d /c/Users/nikot/.local/share/jerry ']'
+ '[' -f /c/Users/nikot/.config/jerry/jerry.conf ']'
+ . /c/Users/nikot/.config/jerry/jerry.conf
++ player=mpv
++ player_arguments=
++ provider=yugen
++ download_dir=/c/Users/nikot
++ manga_dir=/c/Users/nikot/.local/share/jerry/jerry-manga
++ manga_format=image
++ manga_opener=feh
++ history_file=/c/Users/nikot/.local/share/jerry/jerry_history.txt
++ subs_language=english
++ use_external_menu=false
++ image_preview=false
++ json_output=false
++ dub=false
++ score_on_completion=false
++ discord_presence=false
++ presence_script_path=jerrydiscordpresence.py
+ '[' -z mpv ']'
+ '[' -z yugen ']'
+ '[' -z /c/Users/nikot ']'
+ '[' -z /c/Users/nikot/.local/share/jerry/jerry-manga ']'
+ '[' -z image ']'
+ '[' -z feh ']'
+ '[' -z /c/Users/nikot/.local/share/jerry/jerry_history.txt ']'
+ '[' -z english ']'
++ printf %s english
++ cut -c2-
+ subs_language=nglish
+ '[' -z false ']'
+ '[' -z false ']'
+ '[' -z false ']'
+ '[' -z '' ']'
+ sub_or_dub=sub
+ '[' -z false ']'
+ '[' '' = false ']'
+ '[' -z false ']'
+ '[' -z jerrydiscordpresence.py ']'
+ '[' -z '' ']'
+ case "$(uname -s)" in
++ uname -s
+ chafa_options='-f symbols'
+ '[' -z '' ']'
+ show_adult_content=false
+ query=
+ '[' 0 -gt 0 ']'
++ printf %s ''
++ tr ' ' -
++ sed 's/^-//g'
+ query=
+ case "$provider" in
+ provider=yugen
+ '[' false = true ']'
+ main
+ '[' -z '' ']'
+ check_credentials
+ '[' -f /c/Users/nikot/.local/share/jerry/anilist_token.txt ']'
++ cat /c/Users/nikot/.local/share/jerry/anilist_token.txt
+ access_token='no token 4 u >:)'
+ '[' -z 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImZiNjFkYzQ4NWRmMWRiM2I3ZjBlYTdhODc2OGE4MzU4MjU0NzZmNjJkNjAyMzBlNmYyOGYyNDM1YjZkMzcxMTlmODZhOWY3YTUxMDM0NjE5In0.eyJhdWQiOiI5ODU3IiwianRpIjoiZmI2MWRjNDg1ZGYxZGIzYjdmMGVhN2E4NzY4YTgzNTgyNTQ3NmY2MmQ2MDIzMGU2ZjI4ZjI0MzViNmQzNzExOWY4NmE5ZjdhNTEwMzQ2MTkiLCJpYXQiOjE3MTQ0NTI2OTQsIm5iZiI6MTcxNDQ1MjY5NCwiZXhwIjoxNzQ1OTg4Njk0LCJzdWIiOiI2MDMyODU0Iiwic2NvcGVzIjpbXX0.wTQzoHY80UV_pG0cI741EstosOq-imLyXDMmFrb9kStUYcPc2ACZO1WpvmbzdM_apmLJso9FjpacTvW2ZGBxAykXyTxNvGkKTWqPX0U5d5dcXzC32Anp21RTnXYMlJXnkh8NpQ3vska36Drw-Qt3tUNGfgZn36Am_hWRggDPqC4Yzx7urDxPTA9FR2J5JQTLmwfxkAj4OBInhqNycOjkoRG6770zixvklO90A_3Sqple4NchWjj1eMDX5qpNWYfKRIMsLYZbN5g-DXkq-FrZWWc3ffSSLy7VK_sNrM2MWiNliwsgFYcKK_ADHwMSPE530SQVjKhSJ0oZCZvsHKiTdZjBxoDRrsc0D12oV5zh57u_5-Ey-vdTi_vXvk8hjh--3s9LyKOOs6xCHUvzwtjPYYptmVRLhpCRO2aP0hMzmf4iGbWhkLvbBGsAScdQfi6LNjEw0fkdvCSfr70-ghC-8JY3G8S_loILNkX7fzbuuxGXRV1Ycf4XWUrh6d-3MD1HIWPdQVENy60o22o3X4KYsxzzzirT_4ZZ7PfjW0BbtHCHy3PC9v-ZRftazqOZdrUKw69jBMqufej47iZTZuK2KpRGb8CChIJAe5KVsK4sQ1kseWeFtVWhmIr-slHamYvshZYzNqVGDK6MzlNBgi6LT20t4WZKwRwNuvEv_qYGezA' ']'
+ '[' -f /c/Users/nikot/.local/share/jerry/anilist_user_id.txt ']'
++ cat /c/Users/nikot/.local/share/jerry/anilist_user_id.txt
+ user_id=
+ '[' -z 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImZiNjFkYzQ4NWRmMWRiM2I3ZjBlYTdhODc2OGE4MzU4MjU0NzZmNjJkNjAyMzBlNmYyOGYyNDM1YjZkMzcxMTlmODZhOWY3YTUxMDM0NjE5In0.eyJhdWQiOiI5ODU3IiwianRpIjoiZmI2MWRjNDg1ZGYxZGIzYjdmMGVhN2E4NzY4YTgzNTgyNTQ3NmY2MmQ2MDIzMGU2ZjI4ZjI0MzViNmQzNzExOWY4NmE5ZjdhNTEwMzQ2MTkiLCJpYXQiOjE3MTQ0NTI2OTQsIm5iZiI6MTcxNDQ1MjY5NCwiZXhwIjoxNzQ1OTg4Njk0LCJzdWIiOiI2MDMyODU0Iiwic2NvcGVzIjpbXX0.wTQzoHY80UV_pG0cI741EstosOq-imLyXDMmFrb9kStUYcPc2ACZO1WpvmbzdM_apmLJso9FjpacTvW2ZGBxAykXyTxNvGkKTWqPX0U5d5dcXzC32Anp21RTnXYMlJXnkh8NpQ3vska36Drw-Qt3tUNGfgZn36Am_hWRggDPqC4Yzx7urDxPTA9FR2J5JQTLmwfxkAj4OBInhqNycOjkoRG6770zixvklO90A_3Sqple4NchWjj1eMDX5qpNWYfKRIMsLYZbN5g-DXkq-FrZWWc3ffSSLy7VK_sNrM2MWiNliwsgFYcKK_ADHwMSPE530SQVjKhSJ0oZCZvsHKiTdZjBxoDRrsc0D12oV5zh57u_5-Ey-vdTi_vXvk8hjh--3s9LyKOOs6xCHUvzwtjPYYptmVRLhpCRO2aP0hMzmf4iGbWhkLvbBGsAScdQfi6LNjEw0fkdvCSfr70-ghC-8JY3G8S_loILNkX7fzbuuxGXRV1Ycf4XWUrh6d-3MD1HIWPdQVENy60o22o3X4KYsxzzzirT_4ZZ7PfjW0BbtHCHy3PC9v-ZRftazqOZdrUKw69jBMqufej47iZTZuK2KpRGb8CChIJAe5KVsK4sQ1kseWeFtVWhmIr-slHamYvshZYzNqVGDK6MzlNBgi6LT20t4WZKwRwNuvEv_qYGezA' ']'
+ '[' -z '' ']'
++ curl -s -X POST https://graphql.anilist.co -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImZiNjFkYzQ4NWRmMWRiM2I3ZjBlYTdhODc2OGE4MzU4MjU0NzZmNjJkNjAyMzBlNmYyOGYyNDM1YjZkMzcxMTlmODZhOWY3YTUxMDM0NjE5In0.eyJhdWQiOiI5ODU3IiwianRpIjoiZmI2MWRjNDg1ZGYxZGIzYjdmMGVhN2E4NzY4YTgzNTgyNTQ3NmY2MmQ2MDIzMGU2ZjI4ZjI0MzViNmQzNzExOWY4NmE5ZjdhNTEwMzQ2MTkiLCJpYXQiOjE3MTQ0NTI2OTQsIm5iZiI6MTcxNDQ1MjY5NCwiZXhwIjoxNzQ1OTg4Njk0LCJzdWIiOiI2MDMyODU0Iiwic2NvcGVzIjpbXX0.wTQzoHY80UV_pG0cI741EstosOq-imLyXDMmFrb9kStUYcPc2ACZO1WpvmbzdM_apmLJso9FjpacTvW2ZGBxAykXyTxNvGkKTWqPX0U5d5dcXzC32Anp21RTnXYMlJXnkh8NpQ3vska36Drw-Qt3tUNGfgZn36Am_hWRggDPqC4Yzx7urDxPTA9FR2J5JQTLmwfxkAj4OBInhqNycOjkoRG6770zixvklO90A_3Sqple4NchWjj1eMDX5qpNWYfKRIMsLYZbN5g-DXkq-FrZWWc3ffSSLy7VK_sNrM2MWiNliwsgFYcKK_ADHwMSPE530SQVjKhSJ0oZCZvsHKiTdZjBxoDRrsc0D12oV5zh57u_5-Ey-vdTi_vXvk8hjh--3s9LyKOOs6xCHUvzwtjPYYptmVRLhpCRO2aP0hMzmf4iGbWhkLvbBGsAScdQfi6LNjEw0fkdvCSfr70-ghC-8JY3G8S_loILNkX7fzbuuxGXRV1Ycf4XWUrh6d-3MD1HIWPdQVENy60o22o3X4KYsxzzzirT_4ZZ7PfjW0BbtHCHy3PC9v-ZRftazqOZdrUKw69jBMqufej47iZTZuK2KpRGb8CChIJAe5KVsK4sQ1kseWeFtVWhmIr-slHamYvshZYzNqVGDK6MzlNBgi6LT20t4WZKwRwNuvEv_qYGezA' -d '{"query":"query { Viewer { id } }"}'
++ sed -nE 's@.*"id":([0-9]*).*@\1@p'
+ user_id=
+ echo ''
+ '[' -z 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImZiNjFkYzQ4NWRmMWRiM2I3ZjBlYTdhODc2OGE4MzU4MjU0NzZmNjJkNjAyMzBlNmYyOGYyNDM1YjZkMzcxMTlmODZhOWY3YTUxMDM0NjE5In0.eyJhdWQiOiI5ODU3IiwianRpIjoiZmI2MWRjNDg1ZGYxZGIzYjdmMGVhN2E4NzY4YTgzNTgyNTQ3NmY2MmQ2MDIzMGU2ZjI4ZjI0MzViNmQzNzExOWY4NmE5ZjdhNTEwMzQ2MTkiLCJpYXQiOjE3MTQ0NTI2OTQsIm5iZiI6MTcxNDQ1MjY5NCwiZXhwIjoxNzQ1OTg4Njk0LCJzdWIiOiI2MDMyODU0Iiwic2NvcGVzIjpbXX0.wTQzoHY80UV_pG0cI741EstosOq-imLyXDMmFrb9kStUYcPc2ACZO1WpvmbzdM_apmLJso9FjpacTvW2ZGBxAykXyTxNvGkKTWqPX0U5d5dcXzC32Anp21RTnXYMlJXnkh8NpQ3vska36Drw-Qt3tUNGfgZn36Am_hWRggDPqC4Yzx7urDxPTA9FR2J5JQTLmwfxkAj4OBInhqNycOjkoRG6770zixvklO90A_3Sqple4NchWjj1eMDX5qpNWYfKRIMsLYZbN5g-DXkq-FrZWWc3ffSSLy7VK_sNrM2MWiNliwsgFYcKK_ADHwMSPE530SQVjKhSJ0oZCZvsHKiTdZjBxoDRrsc0D12oV5zh57u_5-Ey-vdTi_vXvk8hjh--3s9LyKOOs6xCHUvzwtjPYYptmVRLhpCRO2aP0hMzmf4iGbWhkLvbBGsAScdQfi6LNjEw0fkdvCSfr70-ghC-8JY3G8S_loILNkX7fzbuuxGXRV1Ycf4XWUrh6d-3MD1HIWPdQVENy60o22o3X4KYsxzzzirT_4ZZ7PfjW0BbtHCHy3PC9v-ZRftazqOZdrUKw69jBMqufej47iZTZuK2KpRGb8CChIJAe5KVsK4sQ1kseWeFtVWhmIr-slHamYvshZYzNqVGDK6MzlNBgi6LT20t4WZKwRwNuvEv_qYGezA' ']'
+ '[' -z '' ']'
+ exit 1
+ cleanup
+ rm -rf /tmp/jerry
+ '[' false = true ']'

**Comment by justchokingaround** [comment]
so i deleted your comment bc it contained your token @ninko76 (it appears several times in the log, so just removing it the first time isnt enough). it looks like the authentication fails and ur user_id is empty. try resetting ur credentials entirely, i think that should fix the problem. `rm -rf ~/.local/share/jerry` and then just run jerry again and follow its instructions

**Comment by Qerewe** [comment]
I had the same problem as original OP with the current version (1.9.9 currently). It worked perfectly until I tried adding the discordpresence.py, which required me to make a config file, and it started giving the same "mpv not found" error after setting it up. I tried setting discord presence back to false in the config file and deleting the .py file but it kept not working. I was able to fix it by going to the .config folder and deleting the jerry folder. It seems just the existence of the config file made it not work

**Comment by Lauloque** [comment]
Hi, i'm encountering the same issue as op.

Adding the path to mpv stopped the `not found` error, but instead it just doesn't run anything,

```bash
$ sh -x $(which jerry)
+ JERRY_VERSION=1.9.9
+ anilist_base=https://graphql.anilist.co
+ config_file=/c/Users/Lauloque/.config/jerry/jerry.conf
+ jerry_editor=
+ tmp_dir=/tmp/jerry
+ tmp_position=/tmp/jerry_position
+ trap cleanup EXIT INT TERM
+ applications=/c/Users/Lauloque/.local/share/applications/jerry
+ images_cache_dir=/tmp/jerry/jerry-images
+ command -v bat
+ display=less
+ case "$(uname -s)" in
++ uname -s
+ separator=:
+ path_thing='\'
+ sed=sed
+ command -v notify-send
+ notify=false
+ dep_ch grep sed curl fzf
+ for dep in "$@"
+ command -v grep
+ for dep in "$@"
+ command -v sed
+ for dep in "$@"
+ command -v curl
+ for dep in "$@"
+ command -v fzf
+ '[' '' = true ']'
+ configuration
+ '[' -n '' ']'
+ config_dir=/c/Users/Lauloque/.config/jerry
+ '[' -n '' ']'
+ data_dir=/c/Users/Lauloque/.local/share/jerry
+ '[' '!' -d /c/Users/Lauloque/.local/share/jerry ']'
+ '[' -f /c/Users/Lauloque/.config/jerry/jerry.conf ']'
+ . /c/Users/Lauloque/.config/jerry/jerry.conf
++ player=/c/users/lauloque/scoop/apps/mpv/current/mpv.exe
++ player_arguments=
++ chafa_options=
++ show_adult_content=false
++ provider=yugen
++ download_dir=/c/Users/Lauloque
++ manga_dir=/c/Users/Lauloque/.local/share/jerry/jerry-manga
++ manga_format=image
++ manga_opener=feh
++ history_file=/c/Users/Lauloque/.local/share/jerry/jerry_history.txt
++ subs_language=english
++ use_external_menu=false
++ image_preview=false
++ json_output=false
++ sub_or_dub=sub
++ score_on_completion=false
++ discord_presence=false
++ presence_script_path=jerrydiscordpresence.py
+ '[' -z /c/users/lauloque/scoop/apps/mpv/current/mpv.exe ']'
+ '[' -z yugen ']'
+ '[' -z /c/Users/Lauloque ']'
+ '[' -z /c/Users/Lauloque/.local/share/jerry/jerry-manga ']'
+ '[' -z image ']'
+ '[' -z feh ']'
+ '[' -z /c/Users/Lauloque/.local/share/jerry/jerry_history.txt ']'
+ '[' -z english ']'
++ printf %s english
++ cut -c2-
+ subs_language=nglish
+ '[' -z false ']'
+ '[' -z false ']'
+ '[' -z false ']'
+ '[' -z sub ']'
+ '[' -z false ']'
+ '[' '' = false ']'
+ '[' -z false ']'
+ '[' -z jerrydiscordpresence.py ']'
+ '[' -z '' ']'
+ rofi_prompt_config=/c/Users/Lauloque/.config/rofi/config.rasi
+ '[' -z '' ']'
+ case "$(uname -s)" in
++ uname -s
+ chafa_options='-f sixel'
+ '[' -z false ']'
+ query=
+ '[' 0 -gt 0 ']'
++ printf %s ''
++ tr ' ' -
++ sed 's/^-//g'
+ query=
+ case "$provider" in
+ provider=yugen
+ '[' false = true ']'
+ main
+ '[' -z '' ']'
+ check_credentials
+ '[' -f /c/Users/Lauloque/.local/share/jerry/anilist_token.txt ']'
++ cat /c/Users/Lauloque/.local/share/jerry/anilist_token.txt
+ access_token=my lovely token ♥
+ '[' -z my lovely token ♥ ']'
+ '[' -f /c/Users/Lauloque/.local/share/jerry/anilist_user_id.txt ']'
++ cat /c/Users/Lauloque/.local/share/jerry/anilist_user_id.txt
+ user_id=5623674
+ '[' -z my lovely token ♥ ']'
+ '[' -z 5623674 ']'
+ '[' -z my lovely token ♥ ']'
+ '[' -z 5623674 ']'
+ '[' -n '' ']'
+ '[' -z '' ']'
++ printf 'Watch Anime\nRead Manga\nUpdate (Episodes, Status, Score)\nInfo\nWatch New Anime\nRead New Manga'
++ launcher 'Choose an option: '
++ case "$use_external_menu" in
++ '[' -z '' ']'
++ fzf --cycle --reverse --prompt 'Choose an option: '
++ '[' -n '' ']'
+ mode_choice=Info
+ case "$mode_choice" in
+ command -v jq
+ send_notification 'For this feature to work, you must have jq installed.'
+ '[' false = true ']'
+ '[' false = false ']'
+ '[' -z '' ']'
+ printf '\33[2K\r\033[1;34m%s\n\033[0m' 'For this feature to work, you must have jq installed.'
For this feature to work, you must have jq installed.
+ return
+ exit 1
+ cleanup
+ rm -rf /tmp/jerry
+ '[' false = true ']'
```
