### ISSUE TITLE
Watch new anime does not work

### ISSUE THREAD

**Issue by Hautzii** [justchokingaround/jerry#68]
Hi, I just installed jerry and played around with it, if I choose the first option to watch an anime that's already in my list it works fine but when I choose the option to watch a new one the search bar stays at 0/0 no matter what I type.

**Comment by justchokingaround** [comment]
can you run the script in debug mode and send the log here please? just make sure to remove your token from it

```sh
sh -x $(which jerry)
```

**Comment by Hautzii** [comment]
`+ JERRY_VERSION=1.9.9
+ anilist_base=https://graphql.anilist.co
+ config_file=/Users/arthur/.config/jerry/jerry.conf
+ jerry_editor=
+ tmp_dir=/tmp/jerry
+ tmp_position=/tmp/jerry_position
+ trap cleanup EXIT INT TERM
+ applications=/Users/arthur/.local/share/applications/jerry
+ images_cache_dir=/tmp/jerry/jerry-images
+ command -v bat
+ display=bat
+ case "$(uname -s)" in
++ uname -s
+ sed=gsed
+ player=iina
+ command -v notify-send
+ notify=false
+ dep_ch grep gsed curl fzf
+ for dep in '"$@"'
+ command -v grep
+ for dep in '"$@"'
+ command -v gsed
+ for dep in '"$@"'
+ command -v curl
+ for dep in '"$@"'
+ command -v fzf
+ '[' '' = true ']'
+ configuration
+ '[' -n '' ']'
+ config_dir=/Users/arthur/.config/jerry
+ '[' -n '' ']'
+ data_dir=/Users/arthur/.local/share/jerry
+ '[' '!' -d /Users/arthur/.local/share/jerry ']'
+ '[' -f /Users/arthur/.config/jerry/jerry.conf ']'
+ . /Users/arthur/.config/jerry/jerry.conf
++ player=iina
++ player_arguments=
++ chafa_options=
++ show_adult_content=false
++ provider=yugen
++ download_dir=/Users/arthur
++ manga_dir=/Users/arthur/.local/share/jerry/jerry-manga
++ manga_format=image
++ manga_opener=feh
++ history_file=/Users/arthur/.local/share/jerry/jerry_history.txt
++ subs_language=english
++ use_external_menu=false
++ image_preview=true
++ json_output=false
++ sub_or_dub=sub
++ score_on_completion=false
++ discord_presence=true
++ presence_script_path=jerrydiscordpresence.py
+ '[' -z iina ']'
+ '[' -z yugen ']'
+ '[' -z /Users/arthur ']'
+ '[' -z /Users/arthur/.local/share/jerry/jerry-manga ']'
+ '[' -z image ']'
+ '[' -z feh ']'
+ '[' -z /Users/arthur/.local/share/jerry/jerry_history.txt ']'
+ '[' -z english ']'
++ printf %s english
++ cut -c2-
+ subs_language=nglish
+ '[' -z false ']'
+ '[' -z true ']'
+ '[' -z false ']'
+ '[' -z sub ']'
+ '[' -z false ']'
+ '[' '' = false ']'
+ '[' -z true ']'
+ '[' -z jerrydiscordpresence.py ']'
+ '[' -z '' ']'
+ case "$(uname -s)" in
++ uname -s
+ chafa_options='-f sixel'
+ '[' -z false ']'
+ query=
+ '[' 0 -gt 0 ']'
++ printf %s ''
++ tr ' ' -
++ gsed 's/^-//g'
+ query=
+ case "$provider" in
+ provider=yugen
+ '[' true = true ']'
+ test -d /tmp/jerry/jerry-images
+ mkdir -p /tmp/jerry/jerry-images
+ '[' false = true ']'
+ main
+ '[' -z '' ']'
+ check_credentials
+ '[' -f /Users/arthur/.local/share/jerry/anilist_token.txt ']'
++ cat /Users/arthur/.local/share/jerry/anilist_token.txt
+ access_token= access_token
+ '[' -z access_token ']'
+ '[' -f /Users/arthur/.local/share/jerry/anilist_user_id.txt ']'
++ cat /Users/arthur/.local/share/jerry/anilist_user_id.txt
+ user_id=897479
+ '[' -z access_token ']'
+ '[' -z 897479 ']'
+ '[' -z access_token ']'
+ '[' -z 897479 ']'
+ '[' -n '' ']'
+ '[' -z '' ']'
++ printf 'Watch Anime\nRead Manga\nUpdate (Episodes, Status, Score)\nInfo\nWatch New Anime\nRead New Manga'
++ launcher 'Choose an option: '
++ case "$use_external_menu" in
++ '[' -z '' ']'
++ fzf --cycle --reverse --prompt 'Choose an option: '
++ '[' -n '' ']'
+ mode_choice=
+ case "$mode_choice" in
+ cleanup
+ rm -rf /tmp/jerry
+ '[' true = true ']'
+ '[' false = false ']'
+ killall ueberzugpp
+ rm '/tmp/ueberzugpp-*'`

I replaced the value of the token by access_token

**Comment by justchokingaround** [comment]
do you have fzf and ueberzugpp installed?

**Comment by Hautzii** [comment]
fzf is installed, ueberzugpp doesn't seem to be installed and I can't find any command to install it

**Comment by justchokingaround** [comment]
install it with brew, the package has the same name

**Comment by Hautzii** [comment]
tried it already : 

```
brew install ueberzugpp
Warning: No available formula with the name "ueberzugpp".
==> Searching for similarly named formulae and casks...
Error: No formulae or casks found for ueberzugpp.
```

**Comment by justchokingaround** [comment]
oh, my bad it hasnt been merged into the main package repository yet

```sh
brew install jstkdng/programs/ueberzugpp
```

**Comment by Hautzii** [comment]
it is now installed but the behavior is still the same for both issues

**Comment by justchokingaround** [comment]
can u run it with 

```sh
sh -x $(which jerry) lain
```

**Comment by Hautzii** [comment]
still no images

**Comment by Hautzii** [comment]
yep was removing my token

**Comment by justchokingaround** [comment]
do you have chafa installed and also what's your fzf version?

**Comment by Hautzii** [comment]
I have chafa and my fzf version is 0.51.0

**Comment by justchokingaround** [comment]
is the log u sent the most recent one?

**Comment by Hautzii** [comment]
Yes, it is the most recent one

**Comment by justchokingaround** [comment]
does it work fine without image preview? it seems weird that after choosing an option, the choice variable is empty

**Comment by Hautzii** [comment]
the watch new anime option crashes whatever I type in it, with or without image preview I have to type the anime name directly in the terminal

**Comment by justchokingaround** [comment]
fixed in 48315c4a3f237fb1ba2d7d50c94053f26462689c
please update and try again, should work fine now

```sh
sudo jerry -u
```

**Comment by Hautzii** [comment]
Okay the watch new anime option now works but I still can't get any preview images

**Comment by Hautzii** [comment]
Am I missing something for the previews to load ? I have fzf, ueberzugpp and chafa installed

**Comment by justchokingaround** [comment]
show a screenshot

**Comment by justchokingaround** [comment]
that looks like the warp terminal and afaik it doesn't support sixel for displaying images, so that might be the cause of failure

**Comment by Hautzii** [comment]
Interesting, I just tried on multiple terminals and it doesn't work, no
matter what terminal I'm using.

**Comment by justchokingaround** [comment]
u can check the log with `sh -x $(which jerry)` and then use the program as u normally would. just be careful, bc it contains ur anilist token

**Comment by Hautzii** [comment]
I just checked, the images are being fetched and there's no error about the
loading of the images so no idea where it could come from. Not a big deal
tho.

**Comment by justchokingaround** [comment]
weird
